/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    public void getIssueBookDetails() {
        int book_id = Integer.parseInt(txt_bookId2.getText());
        int student_id = Integer.parseInt(txt_studentId1.getText());
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("select * from issue_book_details where book_id = ? && student_id = ? && status = ?");
            ps.setInt(1, book_id);
            ps.setInt(2, student_id);
            ps.setString(3, "pending");
            ResultSet rs= ps.executeQuery();
            
            if(rs.next()) {
                txt_issueId.setText(rs.getString("id"));
                txt_bookname.setText(rs.getString("book_name"));
                txt_studentname.setText(rs.getString("student_name"));
                txt_issuedate.setText(rs.getString("issue_date"));
                txt_duedate.setText(rs.getString("due_date"));
                txt_bookError.setText("");
            }
            else {
                txt_bookError.setText("No Record Found");
                txt_issueId.setText("");
                txt_bookname.setText("");
                txt_studentname.setText("");
                txt_issuedate.setText("");
                txt_duedate.setText("");
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public boolean returnBook() {
        boolean returned = false;
        int book_id = Integer.parseInt(txt_bookId2.getText());
        int student_id = Integer.parseInt(txt_studentId1.getText());
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update issue_book_details set status = ? where book_id = ? && student_id = ? && status = ?");
            ps.setString(1, "returned");
            ps.setInt(2, book_id);
            ps.setInt(3, student_id);
            ps.setString(4, "pending");
            int rowCount = ps.executeUpdate();
            if(rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Book Returned");
                returned = true;
            }
            else {
                JOptionPane.showMessageDialog(this, "Failed To Return Book");
                returned = false;
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        return returned;
    }
    
    
    
    public void updateCount() {
        int book_id = Integer.parseInt(txt_bookId2.getText());
        try{
            Connection con = DBConnection.getConnection();
            String sql = "Update book_details set quantity = quantity + 1 where book_id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, book_id);
            
            int rowCount = ps.executeUpdate();
            if(rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Book Count Updated");
            }
            else {
                JOptionPane.showMessageDialog(this, "Book Count can not be Updated");
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_duedate = new javax.swing.JLabel();
        txt_studentname = new javax.swing.JLabel();
        txt_issueId = new javax.swing.JLabel();
        txt_bookname = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_bookError = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_issuedate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_studentId1 = new app.bolivia.swing.JCTextField();
        txt_bookId2 = new app.bolivia.swing.JCTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("  Book Details");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 140));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 290, 5));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Book Name :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Issue Id :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student Name :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        txt_duedate.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txt_duedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 170, 30));

        txt_studentname.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txt_studentname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 170, 30));

        txt_issueId.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txt_issueId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 170, 30));

        txt_bookname.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txt_bookname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 170, 30));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Due Date :");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        txt_bookError.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txt_bookError.setForeground(new java.awt.Color(255, 204, 0));
        jPanel4.add(txt_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 280, 40));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Issue Date :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        txt_issuedate.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txt_issuedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txt_issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 170, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 340, 730));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel2.setText("  Return Book");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 110, 220, 90));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 190, 240, 5));

        jLabel18.setFont(new java.awt.Font("Urdu Typesetting", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("Student  Id :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, 90, 30));

        txt_studentId1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_studentId1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_studentId1.setPlaceholder("Enter Student Id...");
        txt_studentId1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentId1FocusLost(evt);
            }
        });
        txt_studentId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentId1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_studentId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, 190, -1));

        txt_bookId2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_bookId2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_bookId2.setPlaceholder("Enter Book Id...");
        txt_bookId2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookId2FocusLost(evt);
            }
        });
        txt_bookId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookId2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_bookId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, 190, -1));

        jLabel22.setFont(new java.awt.Font("Urdu Typesetting", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setText("Book  Id :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 90, 30));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(102, 102, 255));
        jLabel24.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("X");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 60, 50));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(102, 102, 255));
        rSMaterialButtonCircle2.setText("Find Book");
        rSMaterialButtonCircle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle2MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, 310, 80));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle3.setText("Return Book");
        rSMaterialButtonCircle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle3MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, 320, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 650, -1));

        setSize(new java.awt.Dimension(1360, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txt_studentId1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentId1FocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_studentId1FocusLost

    private void txt_studentId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentId1ActionPerformed

    private void txt_bookId2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookId2FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_bookId2FocusLost

    private void txt_bookId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookId2ActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void rSMaterialButtonCircle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2MouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_rSMaterialButtonCircle2MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        getIssueBookDetails();
        
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void rSMaterialButtonCircle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle3MouseClicked

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        if(returnBook()) {
            updateCount();
        }
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private javax.swing.JLabel txt_bookError;
    private app.bolivia.swing.JCTextField txt_bookId2;
    private javax.swing.JLabel txt_bookname;
    private javax.swing.JLabel txt_duedate;
    private javax.swing.JLabel txt_issueId;
    private javax.swing.JLabel txt_issuedate;
    private app.bolivia.swing.JCTextField txt_studentId1;
    private javax.swing.JLabel txt_studentname;
    // End of variables declaration//GEN-END:variables
}
